# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from . import embedder_pb2 as embedder__pb2


class EmbedderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/embedder.v1.EmbedderService/Health',
                request_serializer=embedder__pb2.HealthRequest.SerializeToString,
                response_deserializer=embedder__pb2.HealthResponse.FromString,
                )
        self.Embed = channel.unary_unary(
                '/embedder.v1.EmbedderService/Embed',
                request_serializer=embedder__pb2.EmbedRequest.SerializeToString,
                response_deserializer=embedder__pb2.EmbedResponse.FromString,
                )
        self.EmbedBatch = channel.unary_unary(
                '/embedder.v1.EmbedderService/EmbedBatch',
                request_serializer=embedder__pb2.EmbedBatchRequest.SerializeToString,
                response_deserializer=embedder__pb2.EmbedBatchResponse.FromString,
                )
        self.EmbedStream = channel.unary_stream(
                '/embedder.v1.EmbedderService/EmbedStream',
                request_serializer=embedder__pb2.EmbedStreamRequest.SerializeToString,
                response_deserializer=embedder__pb2.EmbedStreamResponse.FromString,
                )


class EmbedderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Embed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EmbedStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmbedderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=embedder__pb2.HealthRequest.FromString,
                    response_serializer=embedder__pb2.HealthResponse.SerializeToString,
            ),
            'Embed': grpc.unary_unary_rpc_method_handler(
                    servicer.Embed,
                    request_deserializer=embedder__pb2.EmbedRequest.FromString,
                    response_serializer=embedder__pb2.EmbedResponse.SerializeToString,
            ),
            'EmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.EmbedBatch,
                    request_deserializer=embedder__pb2.EmbedBatchRequest.FromString,
                    response_serializer=embedder__pb2.EmbedBatchResponse.SerializeToString,
            ),
            'EmbedStream': grpc.unary_stream_rpc_method_handler(
                    servicer.EmbedStream,
                    request_deserializer=embedder__pb2.EmbedStreamRequest.FromString,
                    response_serializer=embedder__pb2.EmbedStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'embedder.v1.EmbedderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class EmbedderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedder.v1.EmbedderService/Health',
            embedder__pb2.HealthRequest.SerializeToString,
            embedder__pb2.HealthResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Embed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedder.v1.EmbedderService/Embed',
            embedder__pb2.EmbedRequest.SerializeToString,
            embedder__pb2.EmbedResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/embedder.v1.EmbedderService/EmbedBatch',
            embedder__pb2.EmbedBatchRequest.SerializeToString,
            embedder__pb2.EmbedBatchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EmbedStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/embedder.v1.EmbedderService/EmbedStream',
            embedder__pb2.EmbedStreamRequest.SerializeToString,
            embedder__pb2.EmbedStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
