name: llm-service


services:
  qdrant:
    build:
      context: ./qdrant
      dockerfile: dockerfile
    image: qdrant-${COMPOSE_PROJECT_NAME}
    container_name: qdrant-${COMPOSE_PROJECT_NAME}
    env_file: 
      - .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${QDRANT_HTTP_PORT}:${QDRANT_HTTP_PORT}"
      - "${QDRANT_GRPC_PORT}:${QDRANT_GRPC_PORT}"
    volumes:
      - ./qdrant-data:/qdrant/storage
    networks:
      - llm_service_network
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./qdrant


  postgres:
    build:
      context: ./postgres
      dockerfile: dockerfile
    image: postgres-${COMPOSE_PROJECT_NAME}
    container_name: postgres-${COMPOSE_PROJECT_NAME}
    env_file: 
     - .env
     - .common-env.conf
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${POSTGRES_HTTP_PORT}:${POSTGRES_HTTP_PORT}"
    networks:
      - llm_service_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./


  hybrid_embedder:
    build:
      context: ./hybrid_embedder
      dockerfile: dockerfile
    image: hybrid_embedder-${COMPOSE_PROJECT_NAME}
    container_name: hybrid_embedder-${COMPOSE_PROJECT_NAME}
    env_file: 
      - .env
      - .common-env.conf
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${HYBRID_EMBEDDER_GRPC_PORT}:${HYBRID_EMBEDDER_GRPC_PORT}"
    networks:
      - llm_service_network
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./hybrid_embedder


  retriever:
    build:
      context: ./retriever
      dockerfile: dockerfile
    image: retriever-${COMPOSE_PROJECT_NAME}
    container_name: retriever-${COMPOSE_PROJECT_NAME}
    env_file: 
      - .env
      - .common-env.conf
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${RETRIEVER_GRPC_PORT}:${RETRIEVER_GRPC_PORT}"
    networks:
      - llm_service_network
    restart: ${DOCKER_CONTAINERS_RESTART}
    depends_on:
      - qdrant
      - hybrid_embedder
    develop:
      watch:
       - action: rebuild
         path: ./retriever


  # ingestor:
  #  build:
  #    context: ./ingestor
  #    dockerfile: dockerfile
  #  image: ingestor-${COMPOSE_PROJECT_NAME}
  #  container_name: ingestor-${COMPOSE_PROJECT_NAME}
  #  env_file: 
  #    - .env
  #    - .common-env.conf
  #  environment:
  #    RUNNING_INSIDE_DOCKER: 1
  #    COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  #  ports:
  #    - "${INGESTOR_HTTP_PORT}:${INGESTOR_HTTP_PORT}"
  #  networks:
  #    - llm_service_network
  #  restart: ${DOCKER_CONTAINERS_RESTART}
  #  depends_on:
  #    - qdrant
  #    - hybrid_embedder
  #  develop:
  #    watch:
  #      - action: rebuild
  #        path: ./ingestor


  # vllm_math:
  #   build:
  #     context: ./vllm_math
  #     dockerfile: dockerfile
  #   image: vllm_math-${COMPOSE_PROJECT_NAME}
  #   container_name: vllm_math-${COMPOSE_PROJECT_NAME}
  #   env_file: 
  #     - .env
  #     - .vllm-env.conf
  #     - ./vllm_math/.conf
  #   environment:
  #     RUNNING_INSIDE_DOCKER: 1
  #     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  #     HUGGING_FACE_HUB_TOKEN: ${HUGGING_FACE_HUB_TOKEN}
  #   ports:
  #     - "${VLLM_MATH_PORT:-8000}:${VLLM_MATH_PORT:-8000}"
  #   volumes:
  #     - vllm_math_data:/data/hf-cache   
  #   deploy:
  #    resources:
  #      reservations:
  #        devices:
  #          - driver: nvidia
  #            count: all
  #            capabilities: [gpu]
  #   networks:
  #     - llm_service_network
  #   restart: ${DOCKER_CONTAINERS_RESTART}
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./vllm_math


  context_builder:
    build:
      context: ./context_builder
      dockerfile: dockerfile
    image: context_builder-${COMPOSE_PROJECT_NAME}
    container_name: context_builder-${COMPOSE_PROJECT_NAME}
    env_file: 
      - .env
      - .common-env.conf
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${CONTEXT_BUILDER_GRPC_PORT}:${CONTEXT_BUILDER_GRPC_PORT}"
    networks:
      - llm_service_network
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./context_builder


  # personality_builder:
  #   build:
  #     context: ./personality_builder
  #     dockerfile: dockerfile
  #   image: personality_builder-${COMPOSE_PROJECT_NAME}
  #   container_name: personality_builder-${COMPOSE_PROJECT_NAME}
  #   env_file: 
  #     - .env
  #     - .common-env.conf
  #   environment:
  #     RUNNING_INSIDE_DOCKER: 1
  #     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  #   ports:
  #     - "${PERSONALITY_BUILDER_GRPC_PORT}:${PERSONALITY_BUILDER_GRPC_PORT}"
  #   networks:
  #     - llm_service_network
  #   restart: ${DOCKER_CONTAINERS_RESTART}
  #   depends_on:
  #     - policy_builder
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./personality_builder


  # policy_builder:
  #   build:
  #     context: ./policy_builder
  #     dockerfile: dockerfile
  #   image: policy_builder-${COMPOSE_PROJECT_NAME}
  #   container_name: policy_builder-${COMPOSE_PROJECT_NAME}
  #   env_file: 
  #     - .env
  #     - .common-env.conf
  #   environment:
  #     RUNNING_INSIDE_DOCKER: 1
  #     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  #   ports:
  #     - "${POLICY_BUILDER_GRPC_PORT}:${POLICY_BUILDER_GRPC_PORT}"
  #   networks:
  #     - llm_service_network
  #   restart: ${DOCKER_CONTAINERS_RESTART}
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./policy_builder


  # budget_estimator:
  #   build:
  #     context: ./budget_estimator
  #     dockerfile: dockerfile
  #   image: budget_estimator-${COMPOSE_PROJECT_NAME}
  #   container_name: budget_estimator-${COMPOSE_PROJECT_NAME}
  #   env_file: 
  #     - .env
  #     - .common-env.conf
  #     - ./budget_estimator/.conf
  #   environment:
  #     RUNNING_INSIDE_DOCKER: 1
  #     COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
  #   ports:
  #     - "${BUDGET_ESTIMATOR_GRPC_PORT}:${BUDGET_ESTIMATOR_GRPC_PORT}"
  #   networks:
  #     - llm_service_network
  #   restart: ${DOCKER_CONTAINERS_RESTART}
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./budget_estimator

  rag_orchestrator:
    build:
      context: ./rag_orchestrator
      dockerfile: dockerfile
    image: rag_orchestrator-${COMPOSE_PROJECT_NAME}
    container_name: rag_orchestrator-${COMPOSE_PROJECT_NAME}
    env_file: 
      - .env
      - .common-env.conf
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${RAG_ORCHESTRATOR_GRPC_PORT}:${RAG_ORCHESTRATOR_GRPC_PORT}"
    networks:
      - llm_service_network
    restart: ${DOCKER_CONTAINERS_RESTART}
    depends_on:
      - retriever
      - context_builder
    develop:
      watch:
        - action: rebuild
          path: ./rag_orchestrator

  mcp_server:
    build:
      context: ./mcp_server
      dockerfile: dockerfile
    image: mcp_server-${COMPOSE_PROJECT_NAME}
    container_name: mcp_server-${COMPOSE_PROJECT_NAME}
    env_file: 
      - .env
      - .common-env.conf
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${MCP_SERVER_HTTP_PORT}:${MCP_SERVER_HTTP_PORT}"
    networks:
      - llm_service_network
    restart: ${DOCKER_CONTAINERS_RESTART}
    depends_on:
      - rag_orchestrator
    develop:
      watch:
        - action: rebuild
          path: ./mcp_server


networks:
  llm_service_network:
    driver: bridge


volumes:
  vllm_math_data:
    driver: local

  qdrant_data:
    driver: local

  postgres_data:
    driver: local

