FROM node:18-alpine3.21


RUN apk update && \
    apk add --no-cache \
    bash \
    curl \
    ca-certificates \
    tzdata \
  && update-ca-certificates \
  && rm -rf /var/cache/apk/*


RUN adduser -D appuser && \
    mkdir -p /app && \
    chown -R appuser:appuser /app


COPY . /app
WORKDIR /app


RUN chown -R appuser:appuser /app


RUN npm ci


RUN npm run build


RUN chown -R appuser:appuser /app


EXPOSE ${FRONTEND_NGINX_PORT}
USER appuser
ENTRYPOINT ["./entrypoint.sh"]


