name: theorem


services:
  gateway:
    build:
      context: ./gateway
      dockerfile: dockerfile
    image: gateway-${COMPOSE_PROJECT_NAME}
    container_name: gateway-${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - theorem_net
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./gateway


  vllm:
    build:
      context: ./vllm
      dockerfile: dockerfile
    image: vllm-${COMPOSE_PROJECT_NAME}
    container_name: vllm-${COMPOSE_PROJECT_NAME}
    env_file: .env
    environment:
      RUNNING_INSIDE_DOCKER: 1
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - "${VLLM_PORT}:${VLLM_PORT}" 
    volumes:
      - vllm_data:/root/.cache  
    networks:
      - theorem_net
    restart: ${DOCKER_CONTAINERS_RESTART}
    develop:
      watch:
        - action: rebuild
          path: ./vllm 


networks:
  theorem_net:
    driver: bridge
    name: theorem_net


volumes:
  vllm_data:
    driver: local


