FROM debian:12-slim


RUN apt-get update && apt-get install -y --no-install-recommends \
      curl ca-certificates tzdata libgomp1 \
  && update-ca-certificates \
  && rm -rf /var/lib/apt/lists/*


RUN useradd -m -s /bin/bash appuser && \
    mkdir -p /app/gen && \
    mkdir -p /app /data/models && \
    chown -R appuser:appuser /app /data


RUN curl -fsSL https://astral.sh/uv/install.sh -o /tmp/uv-installer.sh
RUN sh /tmp/uv-installer.sh ~/.local/bin \
    && rm /tmp/uv-installer.sh


RUN mv /root/.local/bin/uv /usr/local/bin/uv \
    && mv /root/.local/bin/uvx /usr/local/bin/uvx \
    && chmod +x /usr/local/bin/uv /usr/local/bin/uvx
ENV PATH="/usr/local/bin:${PATH}"


WORKDIR /app


COPY --chown=appuser:appuser pyproject.toml ./
USER appuser
RUN uv sync --no-dev


COPY --chown=appuser:appuser . /app
RUN chmod +x /app/entrypoint.sh


EXPOSE 8000
ENTRYPOINT ["./entrypoint.sh"]