// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"context"

	"github.com/dagahan/theorem/users/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockuserService creates a new instance of mockuserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserService {
	mock := &mockuserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserService is an autogenerated mock type for the userService type
type mockuserService struct {
	mock.Mock
}

type mockuserService_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserService) EXPECT() *mockuserService_Expecter {
	return &mockuserService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockuserService
func (_mock *mockuserService) Create(ctx context.Context, user *models.User) (*models.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockuserService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *mockuserService_Expecter) Create(ctx interface{}, user interface{}) *mockuserService_Create_Call {
	return &mockuserService_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *mockuserService_Create_Call) Run(run func(ctx context.Context, user *models.User)) *mockuserService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserService_Create_Call) Return(user1 *models.User, err error) *mockuserService_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *mockuserService_Create_Call) RunAndReturn(run func(ctx context.Context, user *models.User) (*models.User, error)) *mockuserService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type mockuserService
func (_mock *mockuserService) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserService_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type mockuserService_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *mockuserService_Expecter) GetByEmail(ctx interface{}, email interface{}) *mockuserService_GetByEmail_Call {
	return &mockuserService_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *mockuserService_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *mockuserService_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserService_GetByEmail_Call) Return(user *models.User, err error) *mockuserService_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserService_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *mockuserService_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockuserService
func (_mock *mockuserService) GetByID(ctx context.Context, userID uuid.UUID) (*models.User, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserService_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockuserService_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *mockuserService_Expecter) GetByID(ctx interface{}, userID interface{}) *mockuserService_GetByID_Call {
	return &mockuserService_GetByID_Call{Call: _e.mock.On("GetByID", ctx, userID)}
}

func (_c *mockuserService_GetByID_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *mockuserService_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserService_GetByID_Call) Return(user *models.User, err error) *mockuserService_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserService_GetByID_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*models.User, error)) *mockuserService_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyCredentials provides a mock function for the type mockuserService
func (_mock *mockuserService) VerifyCredentials(ctx context.Context, inputUser *models.User) (bool, error) {
	ret := _mock.Called(ctx, inputUser)

	if len(ret) == 0 {
		panic("no return value specified for VerifyCredentials")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) (bool, error)); ok {
		return returnFunc(ctx, inputUser)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) bool); ok {
		r0 = returnFunc(ctx, inputUser)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = returnFunc(ctx, inputUser)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserService_VerifyCredentials_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyCredentials'
type mockuserService_VerifyCredentials_Call struct {
	*mock.Call
}

// VerifyCredentials is a helper method to define mock.On call
//   - ctx context.Context
//   - inputUser *models.User
func (_e *mockuserService_Expecter) VerifyCredentials(ctx interface{}, inputUser interface{}) *mockuserService_VerifyCredentials_Call {
	return &mockuserService_VerifyCredentials_Call{Call: _e.mock.On("VerifyCredentials", ctx, inputUser)}
}

func (_c *mockuserService_VerifyCredentials_Call) Run(run func(ctx context.Context, inputUser *models.User)) *mockuserService_VerifyCredentials_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserService_VerifyCredentials_Call) Return(b bool, err error) *mockuserService_VerifyCredentials_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockuserService_VerifyCredentials_Call) RunAndReturn(run func(ctx context.Context, inputUser *models.User) (bool, error)) *mockuserService_VerifyCredentials_Call {
	_c.Call.Return(run)
	return _c
}

// newMocksessionService creates a new instance of mocksessionService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocksessionService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocksessionService {
	mock := &mocksessionService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocksessionService is an autogenerated mock type for the sessionService type
type mocksessionService struct {
	mock.Mock
}

type mocksessionService_Expecter struct {
	mock *mock.Mock
}

func (_m *mocksessionService) EXPECT() *mocksessionService_Expecter {
	return &mocksessionService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mocksessionService
func (_mock *mocksessionService) Create(ctx context.Context, userID uuid.UUID) (*models.Session, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Session, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Session); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksessionService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mocksessionService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *mocksessionService_Expecter) Create(ctx interface{}, userID interface{}) *mocksessionService_Create_Call {
	return &mocksessionService_Create_Call{Call: _e.mock.On("Create", ctx, userID)}
}

func (_c *mocksessionService_Create_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *mocksessionService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksessionService_Create_Call) Return(session *models.Session, err error) *mocksessionService_Create_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *mocksessionService_Create_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (*models.Session, error)) *mocksessionService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type mocksessionService
func (_mock *mocksessionService) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksessionService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type mocksessionService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *mocksessionService_Expecter) Delete(ctx interface{}, id interface{}) *mocksessionService_Delete_Call {
	return &mocksessionService_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *mocksessionService_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *mocksessionService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksessionService_Delete_Call) Return(err error) *mocksessionService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksessionService_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *mocksessionService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mocksessionService
func (_mock *mocksessionService) Get(ctx context.Context, id uuid.UUID) (*models.Session, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.Session, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.Session); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocksessionService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mocksessionService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *mocksessionService_Expecter) Get(ctx interface{}, id interface{}) *mocksessionService_Get_Call {
	return &mocksessionService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *mocksessionService_Get_Call) Run(run func(ctx context.Context, id uuid.UUID)) *mocksessionService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksessionService_Get_Call) Return(session *models.Session, err error) *mocksessionService_Get_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *mocksessionService_Get_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.Session, error)) *mocksessionService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshTTL provides a mock function for the type mocksessionService
func (_mock *mocksessionService) RefreshTTL(ctx context.Context, id uuid.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RefreshTTL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocksessionService_RefreshTTL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshTTL'
type mocksessionService_RefreshTTL_Call struct {
	*mock.Call
}

// RefreshTTL is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *mocksessionService_Expecter) RefreshTTL(ctx interface{}, id interface{}) *mocksessionService_RefreshTTL_Call {
	return &mocksessionService_RefreshTTL_Call{Call: _e.mock.On("RefreshTTL", ctx, id)}
}

func (_c *mocksessionService_RefreshTTL_Call) Run(run func(ctx context.Context, id uuid.UUID)) *mocksessionService_RefreshTTL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocksessionService_RefreshTTL_Call) Return(err error) *mocksessionService_RefreshTTL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocksessionService_RefreshTTL_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) error) *mocksessionService_RefreshTTL_Call {
	_c.Call.Return(run)
	return _c
}

// newMocktokenService creates a new instance of mocktokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMocktokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *mocktokenService {
	mock := &mocktokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mocktokenService is an autogenerated mock type for the tokenService type
type mocktokenService struct {
	mock.Mock
}

type mocktokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *mocktokenService) EXPECT() *mocktokenService_Expecter {
	return &mocktokenService_Expecter{mock: &_m.Mock}
}

// CreateAccess provides a mock function for the type mocktokenService
func (_mock *mocktokenService) CreateAccess(claims *models.TokenClaims) (string, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for CreateAccess")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.TokenClaims) (string, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.TokenClaims) string); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.TokenClaims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktokenService_CreateAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAccess'
type mocktokenService_CreateAccess_Call struct {
	*mock.Call
}

// CreateAccess is a helper method to define mock.On call
//   - claims *models.TokenClaims
func (_e *mocktokenService_Expecter) CreateAccess(claims interface{}) *mocktokenService_CreateAccess_Call {
	return &mocktokenService_CreateAccess_Call{Call: _e.mock.On("CreateAccess", claims)}
}

func (_c *mocktokenService_CreateAccess_Call) Run(run func(claims *models.TokenClaims)) *mocktokenService_CreateAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.TokenClaims
		if args[0] != nil {
			arg0 = args[0].(*models.TokenClaims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktokenService_CreateAccess_Call) Return(s string, err error) *mocktokenService_CreateAccess_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mocktokenService_CreateAccess_Call) RunAndReturn(run func(claims *models.TokenClaims) (string, error)) *mocktokenService_CreateAccess_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRefresh provides a mock function for the type mocktokenService
func (_mock *mocktokenService) CreateRefresh(claims *models.TokenClaims) (string, error) {
	ret := _mock.Called(claims)

	if len(ret) == 0 {
		panic("no return value specified for CreateRefresh")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*models.TokenClaims) (string, error)); ok {
		return returnFunc(claims)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.TokenClaims) string); ok {
		r0 = returnFunc(claims)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*models.TokenClaims) error); ok {
		r1 = returnFunc(claims)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktokenService_CreateRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRefresh'
type mocktokenService_CreateRefresh_Call struct {
	*mock.Call
}

// CreateRefresh is a helper method to define mock.On call
//   - claims *models.TokenClaims
func (_e *mocktokenService_Expecter) CreateRefresh(claims interface{}) *mocktokenService_CreateRefresh_Call {
	return &mocktokenService_CreateRefresh_Call{Call: _e.mock.On("CreateRefresh", claims)}
}

func (_c *mocktokenService_CreateRefresh_Call) Run(run func(claims *models.TokenClaims)) *mocktokenService_CreateRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.TokenClaims
		if args[0] != nil {
			arg0 = args[0].(*models.TokenClaims)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktokenService_CreateRefresh_Call) Return(s string, err error) *mocktokenService_CreateRefresh_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mocktokenService_CreateRefresh_Call) RunAndReturn(run func(claims *models.TokenClaims) (string, error)) *mocktokenService_CreateRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateRefresh provides a mock function for the type mocktokenService
func (_mock *mocktokenService) InvalidateRefresh(ctx context.Context, tokenStr string) error {
	ret := _mock.Called(ctx, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateRefresh")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, tokenStr)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mocktokenService_InvalidateRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateRefresh'
type mocktokenService_InvalidateRefresh_Call struct {
	*mock.Call
}

// InvalidateRefresh is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenStr string
func (_e *mocktokenService_Expecter) InvalidateRefresh(ctx interface{}, tokenStr interface{}) *mocktokenService_InvalidateRefresh_Call {
	return &mocktokenService_InvalidateRefresh_Call{Call: _e.mock.On("InvalidateRefresh", ctx, tokenStr)}
}

func (_c *mocktokenService_InvalidateRefresh_Call) Run(run func(ctx context.Context, tokenStr string)) *mocktokenService_InvalidateRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktokenService_InvalidateRefresh_Call) Return(err error) *mocktokenService_InvalidateRefresh_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mocktokenService_InvalidateRefresh_Call) RunAndReturn(run func(ctx context.Context, tokenStr string) error) *mocktokenService_InvalidateRefresh_Call {
	_c.Call.Return(run)
	return _c
}

// IsRefreshInvalidated provides a mock function for the type mocktokenService
func (_mock *mocktokenService) IsRefreshInvalidated(ctx context.Context, token string) (bool, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsRefreshInvalidated")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktokenService_IsRefreshInvalidated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRefreshInvalidated'
type mocktokenService_IsRefreshInvalidated_Call struct {
	*mock.Call
}

// IsRefreshInvalidated is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *mocktokenService_Expecter) IsRefreshInvalidated(ctx interface{}, token interface{}) *mocktokenService_IsRefreshInvalidated_Call {
	return &mocktokenService_IsRefreshInvalidated_Call{Call: _e.mock.On("IsRefreshInvalidated", ctx, token)}
}

func (_c *mocktokenService_IsRefreshInvalidated_Call) Run(run func(ctx context.Context, token string)) *mocktokenService_IsRefreshInvalidated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mocktokenService_IsRefreshInvalidated_Call) Return(b bool, err error) *mocktokenService_IsRefreshInvalidated_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mocktokenService_IsRefreshInvalidated_Call) RunAndReturn(run func(ctx context.Context, token string) (bool, error)) *mocktokenService_IsRefreshInvalidated_Call {
	_c.Call.Return(run)
	return _c
}

// ParseAccess provides a mock function for the type mocktokenService
func (_mock *mocktokenService) ParseAccess(token string) (*models.TokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseAccess")
	}

	var r0 *models.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.TokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.TokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktokenService_ParseAccess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseAccess'
type mocktokenService_ParseAccess_Call struct {
	*mock.Call
}

// ParseAccess is a helper method to define mock.On call
//   - token string
func (_e *mocktokenService_Expecter) ParseAccess(token interface{}) *mocktokenService_ParseAccess_Call {
	return &mocktokenService_ParseAccess_Call{Call: _e.mock.On("ParseAccess", token)}
}

func (_c *mocktokenService_ParseAccess_Call) Run(run func(token string)) *mocktokenService_ParseAccess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktokenService_ParseAccess_Call) Return(tokenClaims *models.TokenClaims, err error) *mocktokenService_ParseAccess_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *mocktokenService_ParseAccess_Call) RunAndReturn(run func(token string) (*models.TokenClaims, error)) *mocktokenService_ParseAccess_Call {
	_c.Call.Return(run)
	return _c
}

// ParseRefresh provides a mock function for the type mocktokenService
func (_mock *mocktokenService) ParseRefresh(token string) (*models.TokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for ParseRefresh")
	}

	var r0 *models.TokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*models.TokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.TokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.TokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mocktokenService_ParseRefresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseRefresh'
type mocktokenService_ParseRefresh_Call struct {
	*mock.Call
}

// ParseRefresh is a helper method to define mock.On call
//   - token string
func (_e *mocktokenService_Expecter) ParseRefresh(token interface{}) *mocktokenService_ParseRefresh_Call {
	return &mocktokenService_ParseRefresh_Call{Call: _e.mock.On("ParseRefresh", token)}
}

func (_c *mocktokenService_ParseRefresh_Call) Run(run func(token string)) *mocktokenService_ParseRefresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mocktokenService_ParseRefresh_Call) Return(tokenClaims *models.TokenClaims, err error) *mocktokenService_ParseRefresh_Call {
	_c.Call.Return(tokenClaims, err)
	return _c
}

func (_c *mocktokenService_ParseRefresh_Call) RunAndReturn(run func(token string) (*models.TokenClaims, error)) *mocktokenService_ParseRefresh_Call {
	_c.Call.Return(run)
	return _c
}
