# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as third__party_dot_protovalidate_dot_buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x06rag.v1\x1a\x35third_party/protovalidate/buf/validate/validate.proto\"\x0f\n\rHealthRequest\"\x87\x01\n\x0eHealthResponse\x12\x19\n\x06status\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18 :Z\xbaHW\x1aU\n\x0bstatus_enum\x12#status must be healthy or unhealthy\x1a!status in [\'healthy\',\'unhealthy\']\"\xbf\x01\n\x05\x43hunk\x12%\n\x02id\x18\x01 \x01(\tB\x19\xbaH\x16r\x14\x32\x12^[0-9a-fA-F-]{36}$\x12)\n\x06\x64oc_id\x18\x02 \x01(\tB\x19\xbaH\x16r\x14\x32\x12^[0-9a-fA-F-]{36}$\x12\"\n\x0cparagraph_id\x18\x03 \x01(\x05\x42\x0c\xbaH\t\x1a\x07\x18\x80\xc2\xd7/(\x01\x12\x1e\n\x08\x63hunk_id\x18\x04 \x01(\x05\x42\x0c\xbaH\t\x1a\x07\x18\x80\xc2\xd7/(\x01\x12 \n\x04text\x18\x05 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\x80@2\x06.*\\S.*\"\xd8\x01\n\x15SemanticSearchRequest\x12!\n\x05query\x18\x01 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\x80 2\x06.*\\S.*\x12\x18\n\x05top_k\x18\x02 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\x64(\x01\x12\"\n\x0fneighbor_window\x18\x03 \x01(\x05\x42\t\xbaH\x06\x1a\x04\x18\n(\x00\x12\x1f\n\x17include_whole_paragraph\x18\x04 \x01(\x08\x12=\n\x0e\x66ilter_doc_ids\x18\n \x03(\tB%\xbaH\"\x92\x01\x1f\x08\x00\x10\x80\x04\x18\x01\"\x16r\x14\x32\x12^[0-9a-fA-F-]{36}$\"\x82\x02\n\x16SemanticSearchResponse\x12,\n\x06\x63hunks\x18\x01 \x03(\x0b\x32\r.rag.v1.ChunkB\r\xbaH\n\x92\x01\x07\x08\x00\x10\xc8\x01\x18\x01\x12\x1e\n\x0bmerged_text\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x18\xc0\x9a\x0c:\x99\x01\xbaH\x95\x01\x1a\x92\x01\n\x17merged_text_when_chunks\x12\x35merged_text must be non-empty when chunks are present\x1a@size(chunks) == 0 || (has(merged_text) && size(merged_text) > 0)2\x96\x01\n\nRagService\x12\x37\n\x06Health\x12\x15.rag.v1.HealthRequest\x1a\x16.rag.v1.HealthResponse\x12O\n\x0eSemanticSearch\x12\x1d.rag.v1.SemanticSearchRequest\x1a\x1e.rag.v1.SemanticSearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._serialized_options = b'\272H\006r\004\020\001\030 '
  _globals['_HEALTHRESPONSE']._loaded_options = None
  _globals['_HEALTHRESPONSE']._serialized_options = b'\272HW\032U\n\013status_enum\022#status must be healthy or unhealthy\032!status in [\'healthy\',\'unhealthy\']'
  _globals['_CHUNK'].fields_by_name['id']._loaded_options = None
  _globals['_CHUNK'].fields_by_name['id']._serialized_options = b'\272H\026r\0242\022^[0-9a-fA-F-]{36}$'
  _globals['_CHUNK'].fields_by_name['doc_id']._loaded_options = None
  _globals['_CHUNK'].fields_by_name['doc_id']._serialized_options = b'\272H\026r\0242\022^[0-9a-fA-F-]{36}$'
  _globals['_CHUNK'].fields_by_name['paragraph_id']._loaded_options = None
  _globals['_CHUNK'].fields_by_name['paragraph_id']._serialized_options = b'\272H\t\032\007\030\200\302\327/(\001'
  _globals['_CHUNK'].fields_by_name['chunk_id']._loaded_options = None
  _globals['_CHUNK'].fields_by_name['chunk_id']._serialized_options = b'\272H\t\032\007\030\200\302\327/(\001'
  _globals['_CHUNK'].fields_by_name['text']._loaded_options = None
  _globals['_CHUNK'].fields_by_name['text']._serialized_options = b'\272H\017r\r\020\001\030\200@2\006.*\\S.*'
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['query']._loaded_options = None
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['query']._serialized_options = b'\272H\017r\r\020\001\030\200 2\006.*\\S.*'
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['top_k']._loaded_options = None
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['top_k']._serialized_options = b'\272H\006\032\004\030d(\001'
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['neighbor_window']._loaded_options = None
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['neighbor_window']._serialized_options = b'\272H\006\032\004\030\n(\000'
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['filter_doc_ids']._loaded_options = None
  _globals['_SEMANTICSEARCHREQUEST'].fields_by_name['filter_doc_ids']._serialized_options = b'\272H\"\222\001\037\010\000\020\200\004\030\001\"\026r\0242\022^[0-9a-fA-F-]{36}$'
  _globals['_SEMANTICSEARCHRESPONSE'].fields_by_name['chunks']._loaded_options = None
  _globals['_SEMANTICSEARCHRESPONSE'].fields_by_name['chunks']._serialized_options = b'\272H\n\222\001\007\010\000\020\310\001\030\001'
  _globals['_SEMANTICSEARCHRESPONSE'].fields_by_name['merged_text']._loaded_options = None
  _globals['_SEMANTICSEARCHRESPONSE'].fields_by_name['merged_text']._serialized_options = b'\272H\006r\004\030\300\232\014'
  _globals['_SEMANTICSEARCHRESPONSE']._loaded_options = None
  _globals['_SEMANTICSEARCHRESPONSE']._serialized_options = b'\272H\225\001\032\222\001\n\027merged_text_when_chunks\0225merged_text must be non-empty when chunks are present\032@size(chunks) == 0 || (has(merged_text) && size(merged_text) > 0)'
  _globals['_HEALTHREQUEST']._serialized_start=76
  _globals['_HEALTHREQUEST']._serialized_end=91
  _globals['_HEALTHRESPONSE']._serialized_start=94
  _globals['_HEALTHRESPONSE']._serialized_end=229
  _globals['_CHUNK']._serialized_start=232
  _globals['_CHUNK']._serialized_end=423
  _globals['_SEMANTICSEARCHREQUEST']._serialized_start=426
  _globals['_SEMANTICSEARCHREQUEST']._serialized_end=642
  _globals['_SEMANTICSEARCHRESPONSE']._serialized_start=645
  _globals['_SEMANTICSEARCHRESPONSE']._serialized_end=903
  _globals['_RAGSERVICE']._serialized_start=906
  _globals['_RAGSERVICE']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
