[project]
name = "ingestor_service"
version = "0.0.1"
requires-python = "==3.12.6"
dependencies = [
    "loguru==0.7.3",
    "colorama==0.4.6",
    "python-dotenv==1.1.1",
    "bcrypt>=4.0.0",
    "chardet>=5.0.0",
    "grpcio==1.75.0",
    "protobuf==6.32.0",
    "protovalidate==1.0.0",
    "qdrant-client==1.15.1",
    "numpy==2.3.2",
    "fastapi==0.115.0",
    "uvicorn[standard]==0.32.0",
    "pydantic==2.10.4",
    "python-multipart==0.0.20",
    "httpx[socks]==0.28.1",
    "SQLAlchemy==2.0.41",
    "psycopg[binary]==3.2.9",
    "asyncpg==0.30.0",
    "aiobotocore==2.24.1",
    "docling==2.55.0",
    "requests[socks]==2.32.5",
]


[project.optional-dependencies]
dev = [
    "ruff==0.12.12",
    "mypy>=1.17.1",
]


[tool.ruff]
target-version = "py312"
line-length = 100


[tool.ruff.lint]
select = ["E", "F", "B", "UP", "I", "W", "N", "ANN", "TCH"]
ignore = ["ANN401", "W293", "F403", "F405"]
unfixable = ["ANN"]


[tool.mypy]
python_version = "3.12"
files = ["src"]
follow_imports = "skip"
strict = true
warn_unused_configs = true
show_error_codes = true
pretty = true

disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true
no_implicit_optional = true
warn_return_any = true
warn_redundant_casts = true
warn_unused_ignores = true
check_untyped_defs = true


plugins = [
  "pydantic.mypy",
]


[mypy-qdrant_client]
ignore_missing_imports = true
[mypy-blingfire]
ignore_missing_imports = true
[mypy-grpc]
ignore_missing_imports = true
[mypy-rust_chunking]
ignore_missing_imports = true

