// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package users

import (
	"context"

	"github.com/dagahan/theorem/users/internal/models"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// newMockuserRepo creates a new instance of mockuserRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockuserRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockuserRepo {
	mock := &mockuserRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockuserRepo is an autogenerated mock type for the userRepo type
type mockuserRepo struct {
	mock.Mock
}

type mockuserRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockuserRepo) EXPECT() *mockuserRepo_Expecter {
	return &mockuserRepo_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type mockuserRepo
func (_mock *mockuserRepo) Create(ctx context.Context, user *models.User) (*models.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) (*models.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *models.User) *models.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *models.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserRepo_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type mockuserRepo_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - user *models.User
func (_e *mockuserRepo_Expecter) Create(ctx interface{}, user interface{}) *mockuserRepo_Create_Call {
	return &mockuserRepo_Create_Call{Call: _e.mock.On("Create", ctx, user)}
}

func (_c *mockuserRepo_Create_Call) Run(run func(ctx context.Context, user *models.User)) *mockuserRepo_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *models.User
		if args[1] != nil {
			arg1 = args[1].(*models.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserRepo_Create_Call) Return(user1 *models.User, err error) *mockuserRepo_Create_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *mockuserRepo_Create_Call) RunAndReturn(run func(ctx context.Context, user *models.User) (*models.User, error)) *mockuserRepo_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByEmail provides a mock function for the type mockuserRepo
func (_mock *mockuserRepo) GetByEmail(ctx context.Context, email string) (*models.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetByEmail")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*models.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *models.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserRepo_GetByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByEmail'
type mockuserRepo_GetByEmail_Call struct {
	*mock.Call
}

// GetByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *mockuserRepo_Expecter) GetByEmail(ctx interface{}, email interface{}) *mockuserRepo_GetByEmail_Call {
	return &mockuserRepo_GetByEmail_Call{Call: _e.mock.On("GetByEmail", ctx, email)}
}

func (_c *mockuserRepo_GetByEmail_Call) Run(run func(ctx context.Context, email string)) *mockuserRepo_GetByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserRepo_GetByEmail_Call) Return(user *models.User, err error) *mockuserRepo_GetByEmail_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserRepo_GetByEmail_Call) RunAndReturn(run func(ctx context.Context, email string) (*models.User, error)) *mockuserRepo_GetByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type mockuserRepo
func (_mock *mockuserRepo) GetByID(ctx context.Context, id uuid.UUID) (*models.User, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *models.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*models.User, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *models.User); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockuserRepo_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type mockuserRepo_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *mockuserRepo_Expecter) GetByID(ctx interface{}, id interface{}) *mockuserRepo_GetByID_Call {
	return &mockuserRepo_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *mockuserRepo_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *mockuserRepo_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockuserRepo_GetByID_Call) Return(user *models.User, err error) *mockuserRepo_GetByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *mockuserRepo_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*models.User, error)) *mockuserRepo_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// newMockhasher creates a new instance of mockhasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhasher {
	mock := &mockhasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhasher is an autogenerated mock type for the hasher type
type mockhasher struct {
	mock.Mock
}

type mockhasher_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhasher) EXPECT() *mockhasher_Expecter {
	return &mockhasher_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function for the type mockhasher
func (_mock *mockhasher) Compare(hash string, password string) (bool, error) {
	ret := _mock.Called(hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (bool, error)); ok {
		return returnFunc(hash, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) bool); ok {
		r0 = returnFunc(hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(hash, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockhasher_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type mockhasher_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - hash string
//   - password string
func (_e *mockhasher_Expecter) Compare(hash interface{}, password interface{}) *mockhasher_Compare_Call {
	return &mockhasher_Compare_Call{Call: _e.mock.On("Compare", hash, password)}
}

func (_c *mockhasher_Compare_Call) Run(run func(hash string, password string)) *mockhasher_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockhasher_Compare_Call) Return(b bool, err error) *mockhasher_Compare_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *mockhasher_Compare_Call) RunAndReturn(run func(hash string, password string) (bool, error)) *mockhasher_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type mockhasher
func (_mock *mockhasher) Hash(password string) (string, error) {
	ret := _mock.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(password)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockhasher_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type mockhasher_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - password string
func (_e *mockhasher_Expecter) Hash(password interface{}) *mockhasher_Hash_Call {
	return &mockhasher_Hash_Call{Call: _e.mock.On("Hash", password)}
}

func (_c *mockhasher_Hash_Call) Run(run func(password string)) *mockhasher_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockhasher_Hash_Call) Return(s string, err error) *mockhasher_Hash_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *mockhasher_Hash_Call) RunAndReturn(run func(password string) (string, error)) *mockhasher_Hash_Call {
	_c.Call.Return(run)
	return _c
}
