# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: budget_estimator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'budget_estimator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as third__party_dot_protovalidate_dot_buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62udget_estimator.proto\x12\x10\x62udget_estimator\x1a\x35third_party/protovalidate/buf/validate/validate.proto\"\x0f\n\rHealthRequest\")\n\x0eHealthResponse\x12\x17\n\x06status\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\"\x14\n\x12\x42uildPolicyRequest\"U\n\x13\x42uildPolicyResponse\x12\x1e\n\rpolicy_header\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t2\xbf\x01\n\x14PolicyBuilderService\x12K\n\x06Health\x12\x1f.budget_estimator.HealthRequest\x1a .budget_estimator.HealthResponse\x12Z\n\x0b\x42uildPolicy\x12$.budget_estimator.BuildPolicyRequest\x1a%.budget_estimator.BuildPolicyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'budget_estimator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_BUILDPOLICYRESPONSE'].fields_by_name['policy_header']._loaded_options = None
  _globals['_BUILDPOLICYRESPONSE'].fields_by_name['policy_header']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_HEALTHREQUEST']._serialized_start=99
  _globals['_HEALTHREQUEST']._serialized_end=114
  _globals['_HEALTHRESPONSE']._serialized_start=116
  _globals['_HEALTHRESPONSE']._serialized_end=157
  _globals['_BUILDPOLICYREQUEST']._serialized_start=159
  _globals['_BUILDPOLICYREQUEST']._serialized_end=179
  _globals['_BUILDPOLICYRESPONSE']._serialized_start=181
  _globals['_BUILDPOLICYRESPONSE']._serialized_end=266
  _globals['_POLICYBUILDERSERVICE']._serialized_start=269
  _globals['_POLICYBUILDERSERVICE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
