# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
from . import hybrid_embedder_pb2 as hybrid__embedder__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in hybrid_embedder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HybridEmbedderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/hybrid_embedder.v1.HybridEmbedderService/Health',
                request_serializer=hybrid__embedder__pb2.HealthRequest.SerializeToString,
                response_deserializer=hybrid__embedder__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.DenseEmbed = channel.unary_unary(
                '/hybrid_embedder.v1.HybridEmbedderService/DenseEmbed',
                request_serializer=hybrid__embedder__pb2.DenseEmbedRequest.SerializeToString,
                response_deserializer=hybrid__embedder__pb2.DenseEmbedResponse.FromString,
                _registered_method=True)
        self.DenseEmbedBatch = channel.unary_unary(
                '/hybrid_embedder.v1.HybridEmbedderService/DenseEmbedBatch',
                request_serializer=hybrid__embedder__pb2.DenseEmbedBatchRequest.SerializeToString,
                response_deserializer=hybrid__embedder__pb2.DenseEmbedBatchResponse.FromString,
                _registered_method=True)
        self.SparseEmbed = channel.unary_unary(
                '/hybrid_embedder.v1.HybridEmbedderService/SparseEmbed',
                request_serializer=hybrid__embedder__pb2.SparseEmbedRequest.SerializeToString,
                response_deserializer=hybrid__embedder__pb2.SparseEmbedResponse.FromString,
                _registered_method=True)
        self.SparseEmbedBatch = channel.unary_unary(
                '/hybrid_embedder.v1.HybridEmbedderService/SparseEmbedBatch',
                request_serializer=hybrid__embedder__pb2.SparseEmbedBatchRequest.SerializeToString,
                response_deserializer=hybrid__embedder__pb2.SparseEmbedBatchResponse.FromString,
                _registered_method=True)


class HybridEmbedderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DenseEmbed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DenseEmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SparseEmbed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SparseEmbedBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HybridEmbedderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=hybrid__embedder__pb2.HealthRequest.FromString,
                    response_serializer=hybrid__embedder__pb2.HealthResponse.SerializeToString,
            ),
            'DenseEmbed': grpc.unary_unary_rpc_method_handler(
                    servicer.DenseEmbed,
                    request_deserializer=hybrid__embedder__pb2.DenseEmbedRequest.FromString,
                    response_serializer=hybrid__embedder__pb2.DenseEmbedResponse.SerializeToString,
            ),
            'DenseEmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.DenseEmbedBatch,
                    request_deserializer=hybrid__embedder__pb2.DenseEmbedBatchRequest.FromString,
                    response_serializer=hybrid__embedder__pb2.DenseEmbedBatchResponse.SerializeToString,
            ),
            'SparseEmbed': grpc.unary_unary_rpc_method_handler(
                    servicer.SparseEmbed,
                    request_deserializer=hybrid__embedder__pb2.SparseEmbedRequest.FromString,
                    response_serializer=hybrid__embedder__pb2.SparseEmbedResponse.SerializeToString,
            ),
            'SparseEmbedBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SparseEmbedBatch,
                    request_deserializer=hybrid__embedder__pb2.SparseEmbedBatchRequest.FromString,
                    response_serializer=hybrid__embedder__pb2.SparseEmbedBatchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hybrid_embedder.v1.HybridEmbedderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hybrid_embedder.v1.HybridEmbedderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HybridEmbedderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hybrid_embedder.v1.HybridEmbedderService/Health',
            hybrid__embedder__pb2.HealthRequest.SerializeToString,
            hybrid__embedder__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DenseEmbed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hybrid_embedder.v1.HybridEmbedderService/DenseEmbed',
            hybrid__embedder__pb2.DenseEmbedRequest.SerializeToString,
            hybrid__embedder__pb2.DenseEmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DenseEmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hybrid_embedder.v1.HybridEmbedderService/DenseEmbedBatch',
            hybrid__embedder__pb2.DenseEmbedBatchRequest.SerializeToString,
            hybrid__embedder__pb2.DenseEmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SparseEmbed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hybrid_embedder.v1.HybridEmbedderService/SparseEmbed',
            hybrid__embedder__pb2.SparseEmbedRequest.SerializeToString,
            hybrid__embedder__pb2.SparseEmbedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SparseEmbedBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hybrid_embedder.v1.HybridEmbedderService/SparseEmbedBatch',
            hybrid__embedder__pb2.SparseEmbedBatchRequest.SerializeToString,
            hybrid__embedder__pb2.SparseEmbedBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
