# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: question_builder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'question_builder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as third__party_dot_protovalidate_dot_buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16question_builder.proto\x12\x13question_builder.v1\x1a\x35third_party/protovalidate/buf/validate/validate.proto\"\x0f\n\rHealthRequest\"J\n\x0eHealthResponse\x12\x19\n\x06status\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12\x1d\n\nllm_status\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \">\n\x16ProcessQuestionRequest\x12$\n\x08raw_text\x18\x01 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\x80@2\x06.*\\S.*\"\xbb\x01\n\x17ProcessQuestionResponse\x12%\n\x11original_question\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80@\x12%\n\x11\x65xpanded_question\x18\x02 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80@\x12(\n expanded_question_semantic_parts\x18\x03 \x03(\t\x12\x0f\n\x07success\x18\x04 \x01(\x08\x12\x17\n\x05\x65rror\x18\x05 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x10\x32\xd9\x01\n\x16QuestionBuilderService\x12Q\n\x06Health\x12\".question_builder.v1.HealthRequest\x1a#.question_builder.v1.HealthResponse\x12l\n\x0fProcessQuestion\x12+.question_builder.v1.ProcessQuestionRequest\x1a,.question_builder.v1.ProcessQuestionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'question_builder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['llm_status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['llm_status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_PROCESSQUESTIONREQUEST'].fields_by_name['raw_text']._loaded_options = None
  _globals['_PROCESSQUESTIONREQUEST'].fields_by_name['raw_text']._serialized_options = b'\272H\017r\r\020\001\030\200@2\006.*\\S.*'
  _globals['_PROCESSQUESTIONRESPONSE'].fields_by_name['original_question']._loaded_options = None
  _globals['_PROCESSQUESTIONRESPONSE'].fields_by_name['original_question']._serialized_options = b'\272H\007r\005\020\001\030\200@'
  _globals['_PROCESSQUESTIONRESPONSE'].fields_by_name['expanded_question']._loaded_options = None
  _globals['_PROCESSQUESTIONRESPONSE'].fields_by_name['expanded_question']._serialized_options = b'\272H\007r\005\020\001\030\200@'
  _globals['_PROCESSQUESTIONRESPONSE'].fields_by_name['error']._loaded_options = None
  _globals['_PROCESSQUESTIONRESPONSE'].fields_by_name['error']._serialized_options = b'\272H\005r\003\030\200\020'
  _globals['_HEALTHREQUEST']._serialized_start=102
  _globals['_HEALTHREQUEST']._serialized_end=117
  _globals['_HEALTHRESPONSE']._serialized_start=119
  _globals['_HEALTHRESPONSE']._serialized_end=193
  _globals['_PROCESSQUESTIONREQUEST']._serialized_start=195
  _globals['_PROCESSQUESTIONREQUEST']._serialized_end=257
  _globals['_PROCESSQUESTIONRESPONSE']._serialized_start=260
  _globals['_PROCESSQUESTIONRESPONSE']._serialized_end=447
  _globals['_QUESTIONBUILDERSERVICE']._serialized_start=450
  _globals['_QUESTIONBUILDERSERVICE']._serialized_end=667
# @@protoc_insertion_point(module_scope)
