# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retriever.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'retriever.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as third__party_dot_protovalidate_dot_buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fretriever.proto\x12\x0cretriever.v1\x1a\x35third_party/protovalidate/buf/validate/validate.proto\"\x0f\n\rHealthRequest\"\xc3\x01\n\x0eHealthResponse\x12\x19\n\x06status\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12\"\n\x0f\x65mbedder_status\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12 \n\rqdrant_status\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12%\n\x11\x65mbedder_model_id\x18\x06 \x01(\tB\n\xbaH\x07r\x05\x10\x00\x18\x80\x02\x12)\n\x0c\x65mbedder_dim\x18\x07 \x01(\x05\x42\x13\xbaH\x10\x1a\x0e\x18\x80 (\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01\"n\n\x0fRetrieveRequest\x12$\n\x08question\x18\x01 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\x80@2\x06.*\\S.*\x12\x35\n\x0f\x63ollection_name\x18\x03 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18\x80\x01\x32\x10^[a-zA-Z0-9_-]+$\"\xb8\x01\n\x0eRetrieveResult\x12\x1a\n\x06\x64oc_id\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x80\x02\x12\x1d\n\x0cparagraph_id\x18\x02 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00\x12\x19\n\x08\x63hunk_id\x18\x03 \x01(\x05\x42\x07\xbaH\x04\x1a\x02(\x00\x12\x19\n\x04text\x18\x04 \x01(\tB\x0b\xbaH\x08r\x06\x10\x00\x18\x80\x80\x04\x12\r\n\x05pages\x18\x05 \x03(\x05\x12&\n\x05score\x18\x06 \x01(\x01\x42\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\x00\x00\x00\xf0?)\x00\x00\x00\x00\x00\x00\x00\x00\"k\n\x10RetrieveResponse\x12-\n\x07results\x18\x01 \x03(\x0b\x32\x1c.retriever.v1.RetrieveResult\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x05\x65rror\x18\x03 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x10\x32\xa2\x01\n\x10RetrieverService\x12\x43\n\x06Health\x12\x1b.retriever.v1.HealthRequest\x1a\x1c.retriever.v1.HealthResponse\x12I\n\x08Retrieve\x12\x1d.retriever.v1.RetrieveRequest\x1a\x1e.retriever.v1.RetrieveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retriever_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['qdrant_status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['qdrant_status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_model_id']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_model_id']._serialized_options = b'\272H\007r\005\020\000\030\200\002'
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_dim']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_dim']._serialized_options = b'\272H\020\032\016\030\200 (\377\377\377\377\377\377\377\377\377\001'
  _globals['_RETRIEVEREQUEST'].fields_by_name['question']._loaded_options = None
  _globals['_RETRIEVEREQUEST'].fields_by_name['question']._serialized_options = b'\272H\017r\r\020\001\030\200@2\006.*\\S.*'
  _globals['_RETRIEVEREQUEST'].fields_by_name['collection_name']._loaded_options = None
  _globals['_RETRIEVEREQUEST'].fields_by_name['collection_name']._serialized_options = b'\272H\031r\027\020\001\030\200\0012\020^[a-zA-Z0-9_-]+$'
  _globals['_RETRIEVERESULT'].fields_by_name['doc_id']._loaded_options = None
  _globals['_RETRIEVERESULT'].fields_by_name['doc_id']._serialized_options = b'\272H\007r\005\020\001\030\200\002'
  _globals['_RETRIEVERESULT'].fields_by_name['paragraph_id']._loaded_options = None
  _globals['_RETRIEVERESULT'].fields_by_name['paragraph_id']._serialized_options = b'\272H\004\032\002(\000'
  _globals['_RETRIEVERESULT'].fields_by_name['chunk_id']._loaded_options = None
  _globals['_RETRIEVERESULT'].fields_by_name['chunk_id']._serialized_options = b'\272H\004\032\002(\000'
  _globals['_RETRIEVERESULT'].fields_by_name['text']._loaded_options = None
  _globals['_RETRIEVERESULT'].fields_by_name['text']._serialized_options = b'\272H\010r\006\020\000\030\200\200\004'
  _globals['_RETRIEVERESULT'].fields_by_name['score']._loaded_options = None
  _globals['_RETRIEVERESULT'].fields_by_name['score']._serialized_options = b'\272H\024\022\022\031\000\000\000\000\000\000\360?)\000\000\000\000\000\000\000\000'
  _globals['_RETRIEVERESPONSE'].fields_by_name['error']._loaded_options = None
  _globals['_RETRIEVERESPONSE'].fields_by_name['error']._serialized_options = b'\272H\005r\003\030\200\020'
  _globals['_HEALTHREQUEST']._serialized_start=88
  _globals['_HEALTHREQUEST']._serialized_end=103
  _globals['_HEALTHRESPONSE']._serialized_start=106
  _globals['_HEALTHRESPONSE']._serialized_end=301
  _globals['_RETRIEVEREQUEST']._serialized_start=303
  _globals['_RETRIEVEREQUEST']._serialized_end=413
  _globals['_RETRIEVERESULT']._serialized_start=416
  _globals['_RETRIEVERESULT']._serialized_end=600
  _globals['_RETRIEVERESPONSE']._serialized_start=602
  _globals['_RETRIEVERESPONSE']._serialized_end=709
  _globals['_RETRIEVERSERVICE']._serialized_start=712
  _globals['_RETRIEVERSERVICE']._serialized_end=874
# @@protoc_insertion_point(module_scope)
