# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings
from . import system_prompt_builder_pb2 as system__prompt__builder__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in system_prompt_builder_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SystemPromptBuilderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/system_prompt_builder.v1.SystemPromptBuilderService/Health',
                request_serializer=system__prompt__builder__pb2.HealthRequest.SerializeToString,
                response_deserializer=system__prompt__builder__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.BuildSystemPrompt = channel.unary_unary(
                '/system_prompt_builder.v1.SystemPromptBuilderService/BuildSystemPrompt',
                request_serializer=system__prompt__builder__pb2.BuildSystemPromptRequest.SerializeToString,
                response_deserializer=system__prompt__builder__pb2.BuildSystemPromptResponse.FromString,
                _registered_method=True)


class SystemPromptBuilderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuildSystemPrompt(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SystemPromptBuilderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=system__prompt__builder__pb2.HealthRequest.FromString,
                    response_serializer=system__prompt__builder__pb2.HealthResponse.SerializeToString,
            ),
            'BuildSystemPrompt': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildSystemPrompt,
                    request_deserializer=system__prompt__builder__pb2.BuildSystemPromptRequest.FromString,
                    response_serializer=system__prompt__builder__pb2.BuildSystemPromptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'system_prompt_builder.v1.SystemPromptBuilderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('system_prompt_builder.v1.SystemPromptBuilderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SystemPromptBuilderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/system_prompt_builder.v1.SystemPromptBuilderService/Health',
            system__prompt__builder__pb2.HealthRequest.SerializeToString,
            system__prompt__builder__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuildSystemPrompt(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/system_prompt_builder.v1.SystemPromptBuilderService/BuildSystemPrompt',
            system__prompt__builder__pb2.BuildSystemPromptRequest.SerializeToString,
            system__prompt__builder__pb2.BuildSystemPromptResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
