# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system_prompt_builder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'system_prompt_builder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as third__party_dot_protovalidate_dot_buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bsystem_prompt_builder.proto\x12\x18system_prompt_builder.v1\x1a\x35third_party/protovalidate/buf/validate/validate.proto\"\x0f\n\rHealthRequest\"U\n\x0eHealthResponse\x12\x19\n\x06status\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12(\n\x15policy_builder_status\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \"\x1a\n\x18\x42uildSystemPromptRequest\"h\n\x19\x42uildSystemPromptResponse\x12!\n\rsystem_prompt\x18\x01 \x01(\tB\n\xbaH\x07r\x05\x10\x01\x18\x90\x66\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x05\x65rror\x18\x03 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x10\x32\xf7\x01\n\x1aSystemPromptBuilderService\x12[\n\x06Health\x12\'.system_prompt_builder.v1.HealthRequest\x1a(.system_prompt_builder.v1.HealthResponse\x12|\n\x11\x42uildSystemPrompt\x12\x32.system_prompt_builder.v1.BuildSystemPromptRequest\x1a\x33.system_prompt_builder.v1.BuildSystemPromptResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_prompt_builder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['policy_builder_status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['policy_builder_status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_BUILDSYSTEMPROMPTRESPONSE'].fields_by_name['system_prompt']._loaded_options = None
  _globals['_BUILDSYSTEMPROMPTRESPONSE'].fields_by_name['system_prompt']._serialized_options = b'\272H\007r\005\020\001\030\220f'
  _globals['_BUILDSYSTEMPROMPTRESPONSE'].fields_by_name['error']._loaded_options = None
  _globals['_BUILDSYSTEMPROMPTRESPONSE'].fields_by_name['error']._serialized_options = b'\272H\005r\003\030\200\020'
  _globals['_HEALTHREQUEST']._serialized_start=112
  _globals['_HEALTHREQUEST']._serialized_end=127
  _globals['_HEALTHRESPONSE']._serialized_start=129
  _globals['_HEALTHRESPONSE']._serialized_end=214
  _globals['_BUILDSYSTEMPROMPTREQUEST']._serialized_start=216
  _globals['_BUILDSYSTEMPROMPTREQUEST']._serialized_end=242
  _globals['_BUILDSYSTEMPROMPTRESPONSE']._serialized_start=244
  _globals['_BUILDSYSTEMPROMPTRESPONSE']._serialized_end=348
  _globals['_SYSTEMPROMPTBUILDERSERVICE']._serialized_start=351
  _globals['_SYSTEMPROMPTBUILDERSERVICE']._serialized_end=598
# @@protoc_insertion_point(module_scope)
