# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rag.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rag.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as third__party_dot_protovalidate_dot_buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trag.proto\x12\x06rag.v1\x1a\x35third_party/protovalidate/buf/validate/validate.proto\"\x0f\n\rHealthRequest\"\xb4\x02\n\x0eHealthResponse\x12\x19\n\x06status\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12\"\n\x0f\x65mbedder_status\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12 \n\rqdrant_status\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x00\x18 \x12%\n\x11\x65mbedder_model_id\x18\x06 \x01(\tB\n\xbaH\x07r\x05\x10\x00\x18\x80\x02\x12)\n\x0c\x65mbedder_dim\x18\x07 \x01(\x05\x42\x13\xbaH\x10\x1a\x0e\x18\x80 (\xff\xff\xff\xff\xff\xff\xff\xff\xff\x01:o\xbaHl\x1aj\n\x0bstatus_enum\x12#status must be healthy or unhealthy\x1a\x36this.status == \'healthy\' || this.status == \'unhealthy\'\"i\n\rSearchRequest\x12!\n\x05query\x18\x01 \x01(\tB\x12\xbaH\x0fr\r\x10\x01\x18\x80@2\x06.*\\S.*\x12\x35\n\x0f\x63ollection_name\x18\x02 \x01(\tB\x1c\xbaH\x19r\x17\x10\x01\x18\x80\x01\x32\x10^[a-zA-Z0-9_-]+$\"S\n\x0eSearchResponse\x12\x17\n\x06result\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x17\n\x05\x65rror\x18\x03 \x01(\tB\x08\xbaH\x05r\x03\x18\x80\x10\x32~\n\nRAGService\x12\x37\n\x06Health\x12\x15.rag.v1.HealthRequest\x1a\x16.rag.v1.HealthResponse\x12\x37\n\x06Search\x12\x15.rag.v1.SearchRequest\x1a\x16.rag.v1.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rag_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['qdrant_status']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['qdrant_status']._serialized_options = b'\272H\006r\004\020\000\030 '
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_model_id']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_model_id']._serialized_options = b'\272H\007r\005\020\000\030\200\002'
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_dim']._loaded_options = None
  _globals['_HEALTHRESPONSE'].fields_by_name['embedder_dim']._serialized_options = b'\272H\020\032\016\030\200 (\377\377\377\377\377\377\377\377\377\001'
  _globals['_HEALTHRESPONSE']._loaded_options = None
  _globals['_HEALTHRESPONSE']._serialized_options = b'\272Hl\032j\n\013status_enum\022#status must be healthy or unhealthy\0326this.status == \'healthy\' || this.status == \'unhealthy\''
  _globals['_SEARCHREQUEST'].fields_by_name['query']._loaded_options = None
  _globals['_SEARCHREQUEST'].fields_by_name['query']._serialized_options = b'\272H\017r\r\020\001\030\200@2\006.*\\S.*'
  _globals['_SEARCHREQUEST'].fields_by_name['collection_name']._loaded_options = None
  _globals['_SEARCHREQUEST'].fields_by_name['collection_name']._serialized_options = b'\272H\031r\027\020\001\030\200\0012\020^[a-zA-Z0-9_-]+$'
  _globals['_SEARCHRESPONSE'].fields_by_name['result']._loaded_options = None
  _globals['_SEARCHRESPONSE'].fields_by_name['result']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_SEARCHRESPONSE'].fields_by_name['error']._loaded_options = None
  _globals['_SEARCHRESPONSE'].fields_by_name['error']._serialized_options = b'\272H\005r\003\030\200\020'
  _globals['_HEALTHREQUEST']._serialized_start=76
  _globals['_HEALTHREQUEST']._serialized_end=91
  _globals['_HEALTHRESPONSE']._serialized_start=94
  _globals['_HEALTHRESPONSE']._serialized_end=402
  _globals['_SEARCHREQUEST']._serialized_start=404
  _globals['_SEARCHREQUEST']._serialized_end=509
  _globals['_SEARCHRESPONSE']._serialized_start=511
  _globals['_SEARCHRESPONSE']._serialized_end=594
  _globals['_RAGSERVICE']._serialized_start=596
  _globals['_RAGSERVICE']._serialized_end=722
# @@protoc_insertion_point(module_scope)
